#!/bin/bash
#
# Created by AJ Canlas
# April 17,2021
# Wokshopfolder location
WSDIR="/etc/midtermfolder"

# First Agument Passer Variable set to 0
FAP=0


# Help argument output
help_workshop(){
  printf "Usage: $0 [action]\nexample:\n\t$0 start\n\t$0 grade\n\n"
}

# Checking viable first argument
check_first_argument(){
  # Checking if first argument is available
  if [ -z "$1" ]
  then
	# Alerts user and prints help
	echo "No action supplied!"
	help_workshop

  # Checking if first argument is help
  elif [ "$1" = "help" ]
  then
	# Print help
	help_workshop
  else
	# Check from workshopfolder if lesson is available
	for i in `ls $WSDIR`
	do
		if [ "$i" = "$1" ]
		then
			# If checked that lesson is available pass it to second
			# function
			bash $WSDIR/$1
			FAP=1
			break
		fi
	done

	# Check if First argument passer is changed
	if [ $FAP -eq 0 ]
	then
		printf "$1 action is not availble\n"
		help_workshop
	fi
  fi
}



# Main function
main(){
	check_first_argument $1
}

# workshop execution
main $1
