#!/bin/bash

source $HOME/.bashrc

ANS="n"
API_KEY="935415758:AAGc-sXokFb-zNYpHeSYvcvQDOSur3HnzUo"
CHAT_ID="508456308"

while [ "$ANS" != "y" ]
do
	echo -n "Full Name:"
	read full_name
	echo -n "username:"
	read user_name
	echo -n "stnumber:"
	read st_number

	echo -n "Full Name: $full_name
User Name: $user_name
Student Number: $st_number 
Is this information correct ? (y/n)"
	read ANS
done

echo $full_name | sudo tee -a /etc/.midtermconfig
echo $user_name | sudo tee -a /etc/.midtermconfig
echo $st_number | sudo tee -a /etc/.midtermconfig 

TASKS=`seq 1 10 | shuf | head -n 3`

CHAT_TEXT="$full_name with the student number of $st_number and user name $user_name is taking the midterm exam"

sudo mkdir -p /tmp/instructions
sudo mkdir -p /tmp/checker

for i in $TASKS;do sudo cp /etc/instructionfolder/$i /tmp/instructions;sudo cp /etc/checker/$i /tmp/checker;done

echo $TASKS | tee -a /etc/.midtermconfig

curl -s --data "chat_id=$CHAT_ID" --data "text=$CHAT_TEXT" 'https://api.telegram.org/bot'$API_KEY'/sendMessage' >> /dev/null

sudo hostnamectl set-hostname $user_name

bash
