#!/bin/bash


echo "MIDTERM INSTRUCTIONS"
for i in `ls /etc/instructions`;
do
	echo "--------------------------------------------------------------------------------------"
	cat /etc/instructions/$i
	echo "--------------------------------------------------------------------------------------"
done
